nothing ka bro
smovidya/pussadusmocu pull request #3
Opened 2024-05-21 14:31 UTC by nwmei82

2024-06-01 17:51 UTC, bunnybunbun37204 requested changes
แก้เป็น page.tsx นะคับ

2024-06-01 17:56 UTC, bunnybunbun37204 approved these changes

2024-06-01 17:56 UTC, bunnybunbun37204 commented on src/app/admin/status/p1.tsx
> +        <option>โครงการ2</option>
ตรงนี้ควร fetch option โครงการจาก database นะคับ

2024-06-01 17:56 UTC, bunnybunbun37204 commented on src/app/mei/page.tsx
อันนี้ลบออกเลยก็ได้ 555555

2024-06-01 17:56 UTC, bunnybunbun37204 commented on src/app/mei/page.tsx
อ๋ออเอาไปใส่หน้า status เลย

2024-06-01 17:56 UTC, bunnybunbun37204 commented on src/utils/constant.ts
เก่งมากแก้คำให้

2024-06-01 17:58 UTC, bunnybunbun37204 requested changes
เก่งมากกงับ

2024-06-01 17:58 UTC, bunnybunbun37204 commented on src/app/mei/popCard.tsx
ถ้าเป็น component ใส่ในโฟลเดอร์แยกต่างหากดีกว่า

2024-06-05 11:16 UTC, nwmei82 commented
ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง

2024-06-05 14:27 UTC, bunnybunbun37204 commented
> ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง

เราเพิ่มข้อมูลใน database ยังคับ

2024-06-05 14:29 UTC, nwmei82 commented
> > ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง
> 
> 
> 
> เราเพิ่มข้อมูลใน database ยังคับ

เพิ่มแล้ว คืออันเดิมที่มันขึ้นแล้วอะไม่ขึ้น ;-;

2024-06-05 15:35 UTC, bunnybunbun37204 commented
> > > ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง
> > 
> > 
> > เราเพิ่มข้อมูลใน database ยังคับ
> 
> เพิ่มแล้ว คืออันเดิมที่มันขึ้นแล้วอะไม่ขึ้น ;-;

แคป db ที่เกี่ยวข้องมาหน่อย

2024-06-05 15:37 UTC, bunnybunbun37204 commented
> > > > ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง
> > > 
> > > 
> > > เราเพิ่มข้อมูลใน database ยังคับ
> > 
> > 
> > เพิ่มแล้ว คืออันเดิมที่มันขึ้นแล้วอะไม่ขึ้น ;-;
> 
> แคป db ที่เกี่ยวข้องมาหน่อย

![image](https://github.com/smovidya/pussadusmocu/assets/70959980/c89ef016-7c6d-4127-b3fa-3d1390f22714)
ตรงนี้ชะมะ

2024-06-05 15:39 UTC, nwmei82 commented
> > > > > ช่วยแก้โหน่ย คือ ทำไมพอไอตัวหน้าหลักมันได้แล้ว แต่ว่าดรอปดาวน์มันขึ้น loading ตลอดเลยอะ งองงงง
> > > > 
> > > > 
> > > > เราเพิ่มข้อมูลใน database ยังคับ
> > > 
> > > 
> > > เพิ่มแล้ว คืออันเดิมที่มันขึ้นแล้วอะไม่ขึ้น ;-;
> > 
> > 
> > แคป db ที่เกี่ยวข้องมาหน่อย
> 
> ![image](https://private-user-images.githubusercontent.com/70959980/336909101-c89ef016-7c6d-4127-b3fa-3d1390f22714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDIyMjMsIm5iZiI6MTcxNzYwMTkyMywicGF0aCI6Ii83MDk1OTk4MC8zMzY5MDkxMDEtYzg5ZWYwMTYtN2M2ZC00MTI3LWIzZmEtM2QxMzkwZjIyNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE1Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjAwODdmNDYyZTdkNGE0ODZiMGFjYzQ4Mzc5ZmUwZTg1Y2M4ZTBiZjdkYjA3MGRhODA5M2Q1YzdjODgyNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XrW3Ne4SUSxZMth1AdMKSX4ev7Gk1XlKAGlTnBQ00sE) ตรงนี้ชะมะ

ใช่ๆ คือวันก่อนตอนทำ Dropdown อะ มันใช้ได้ละนะ แบบขึ้นปกติแล้ว แต่วันนี้ไม่ได้แล้ว ทำไมไม่นู้

2024-06-05 15:57 UTC, bunnybunbun37204 requested changes
ให้แก้เป็นถ้าใช้ `use client ` ให้เขียนโค้ด server เพิ่ม ละค่อย fetch มาคล้ายๆกับตัว Dropdown เลย

2024-06-05 15:57 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
Ok ในไฟล์นี้เราใช้เป็น use client ซึ่งเราไม่สามารถ call prisma client ในหน้านี้ได้ตรงๆ มันเลยคล้ายเราทำ server side render ทำให้เวลามันอัพเดท state ของ drop down แล้วมันไม่เปลี่ยน ทางที่ดี fetch prisma ในโค้ด server นะคับละค่อยดึงมา เหมือนตอนทำ `api.getProject();` 
![image](https://github.com/smovidya/pussadusmocu/assets/70959980/43bcf8d8-716e-4165-9ad7-a0641e4e7ebd)
ในโค้ดพี่ลบทุกอย่างใส่แค่ drop down มันใช้ได้นะ

2024-06-05 15:57 UTC, bunnybunbun37204 commented on src/components/ui/dropdown.tsx
เวลาทำ component เองให้ไปใส่ใน app/_component นะ ใน @/componet มันมาจาก shadcn generate ให้้ ไม่อยากให้ไปแตะ

2024-06-05 15:57 UTC, bunnybunbun37204 commented on src/components/ui/popCard.tsx
ตรงนี้เช่นกัน

2024-06-05 16:21 UTC, nwmei82 commented on src/app/admin/status/page.tsx
ยังไงนะ5555555

2024-06-05 16:22 UTC, nwmei82 commented on src/app/admin/status/page.tsx
หมายถึงไอตรงหน้า status คือไม่สามารถทำแบบนั้นได้ ให้ไปเขียนตรง api ก่อนแล้วค่อยเรียกใช้ แบบนี้บ่

2024-06-05 16:37 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
ใช่แล้วอย่าเขียน backend ในหน้าที่ใช้ use client

2024-06-06 08:29 UTC, nwmei82 commented
ช่วยเช็คไฟล์ api ให้หน่อยฮะ คือกดให้อัปเดตสเตตัสแล้วแต่มันไม่อัปเดตอะ ส่วนอื่นใช้ได้หมดละ เหลือแค่กดยืนยันแล้วอัปเดตสถานะกลับไปเป็น borrowing

2024-06-06 15:56 UTC, bunnybunbun37204 commented
> ช่วยเช็คไฟล์ api ให้หน่อยฮะ คือกดให้อัปเดตสเตตัสแล้วแต่มันไม่อัปเดตอะ ส่วนอื่นใช้ได้หมดละ เหลือแค่กดยืนยันแล้วอัปเดตสถานะกลับไปเป็น borrowing

Ok กำลังเช็คคับ

2024-06-07 16:38 UTC, bunnybunbun37204 requested changes
pull ตัว main โดยใช้ `git pull origin main` ให้โค้ดอัพเดทนะคับ

2024-06-07 16:38 UTC, bunnybunbun37204 commented on src/app/_components/dropdown.tsx
> +      </select>
ตรงนี้มัน filter ได้ไหมนะ

2024-06-07 16:38 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
> +export default async function Page() {
ควรเขียน api แยกนะไม่ควรเรียก prisma ในหน้า Page

2024-06-07 16:38 UTC, bunnybunbun37204 commented on src/app/admin/status/Sta.tsx
> +                />
ตรงนี้มันอัพเดทแต่ละทีคือไปหมดทุกไฟล์ มันเลยน่าจะบัค ละก็ยังไม่อัพเดท database

2024-06-07 16:38 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
> +export type ParcelProjectWithDetails = Parcel_Project & {
ไม่ควรเขียนหน้า Page นะคับสำหรับอะไรที่ติดต่อ database

2024-06-07 16:38 UTC, bunnybunbun37204 commented on src/server/api/routers/project.ts
> +  getProject: publicProcedure.query(async ({ ctx }) => {
อันนี้คือเปลี่ยนทำไมนะ

2024-06-07 17:18 UTC, nwmei82 commented on src/server/api/routers/project.ts
> +  getProject: publicProcedure.query(async ({ ctx }) => {
มัน get ไม่ได้อุ

2024-06-07 17:18 UTC, nwmei82 commented on src/app/admin/status/page.tsx
> +export default async function Page() {
เขียน api ไม่เป็น ช่วยด้วยยยยยย T-T

2024-06-08 05:18 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
> +export default async function Page() {
จริงๆ pull main ละพูดมาใช้ได้เลยนะถ้าเขียนละ

2024-06-08 05:19 UTC, bunnybunbun37204 commented on src/server/api/routers/project.ts
> +  getProject: publicProcedure.query(async ({ ctx }) => {
แต่อันนี้คือได้ใช่ไหมไม่กระทบกับหน้าอื่นใช่มะ

2024-06-08 22:47 UTC, merged