Mei/filter
smovidya/pussadusmocu pull request #6
Opened 2024-06-12 03:46 UTC by nwmei82

2024-06-12 09:08 UTC, nwmei82 commented
พี่เกมไอตรงที่รีเทิร์นกลับไปแล้วจะเพิ่มจำนวนอะ คือหนูต้องไปเขียนแบบใน parcel_project.ts แบบสำหรับอัพเดตจำนวนกลับไปอะ

2024-06-13 04:55 UTC, bunnybunbun37204 commented on src/app/_components/popCard.tsx
> +          </Button>
เค เยี่ยม เพิ่มมตัวที่มันกรอกจำนวนใช้ `<Input/> `ก็ได้

2024-06-13 04:55 UTC, bunnybunbun37204 commented on src/app/admin/status/page.tsx
> +  PrismaClient,
หน้านี้ไม่ควรมี `PrismaClient `นะ ควรทำในโฟลเดอร **server**

2024-06-13 05:01 UTC, nwmei82 commented on src/app/_components/popCard.tsx
> +          </Button>
อะไรคือเพิ่มตัวที่มันกรอกจำนวน

2024-06-13 06:37 UTC, bunnybunbun37204 reviewed
test comment

2024-06-14 07:32 UTC, bunnybunbun37204 requested changes
เก่งมากคับเหม่ย ไปเพิ่มตรงกด return แล้วสถานะต้องเปลี่ยน ตาม flow เลยละก็ให้ทำตัวกันกรอกของที่คืนผิดคับ

2024-06-14 07:32 UTC, bunnybunbun37204 commented on src/server/api/routers/parcel_Project.ts
> +    })
ใน transaction เปลี่ยนสถานะของ parcel_project สำหรับรายการนั้น ให้กลายเป็น **RETURN** ด้วยของเข้าแล้วแต่ตอนนี้สถานะคงเป็น INUSE คับ

2024-06-14 07:32 UTC, bunnybunbun37204 commented on src/app/_components/popCard.tsx
> +          </>
ตรงนี้เขียนกันไม่ให้กรอกของที่เข้า stock มากกว่าของที่ยืมไปด้วย เช่น ยืมไป 7 ไม่ควรคืนเกิน 7

2024-06-14 15:34 UTC, merged